### ISSUE TITLE
Not always loading

### ISSUE THREAD

**Issue by BenderBRod** [drunohazarb/4chan-captcha-solver#10]
Up to date firefox and tampermonkey
I tried both versions
Most of the time it just doesnt do anything but when i loads its very fast

**Comment by slabodan** [comment]
anything in the console?

**Comment by AlifianK** [comment]
Having the same problem. Here's the console but I don't think it says anything useful. Using the WebAssembly version, switched to the js version, also not working.
![image](https://github.com/drunohazarb/4chan-captcha-solver/assets/50392169/d070bfea-ec40-4c67-b2d7-d68d6048dbc9)

**Comment by slabodan** [comment]
weird, 1.4.2 version works (mostly) fine for me on ff and chrome except when sometimes i get a tfjs related error

**Comment by AlifianK** [comment]
> weird, 1.4.2 version works (mostly) fine for me on ff and chrome except when sometimes i get a tfjs related error

Hmmm, it seems like a Tampermonkey problem. Installed Violentmonkey in the same browser (Edge), it works.

**Comment by MooseZM** [comment]
i was having the same problem on Tampermonkey on Opera GX. Tried the script on Violentmonkey and it works fine

**Comment by BenderBRod** [comment]
![solvererror](https://github.com/drunohazarb/4chan-captcha-solver/assets/17176020/2466f439-7eff-4c72-8342-f47d2f3397dd)

**Comment by slabodan** [comment]
source map warnings are whatever, i guess try violentmonkey then

**Comment by AlifianK** [comment]
> source map warnings are whatever, i guess try violentmonkey then

Yeah, but it's a shame that violentmonkey also shit itself on Chrome on some boards when using 4chanX JSON index, but that's unrelated and I already filed an issue there.

**Comment by BenderBRod** [comment]
Just using a different addon is not a great solution
I have multiple scripts running and i dont wanna switch
It worked perfectly until this version

**Comment by slabodan** [comment]
if you replace this part 
```
    window.addEventListener("load", function() { // uBlock Origin on chrome seems to prevent the DOMContentLoaded event from firing...
      observer.observe(document.body, { attributes: true, childList: true, subtree: true });
  
      if(navigator.userAgent.toLowerCase().indexOf('firefox') !== -1){ // request canvas permission on firefox
        let image = new Image(16, 16);
        imageFromCanvas(image, image, 0);
      }
    });
```
with
```
    window.setTimeout(function() {
      observer.observe(document.body, { attributes: true, childList: true, subtree: true });
  
      if(navigator.userAgent.toLowerCase().indexOf('firefox') !== -1){ // request canvas permission on firefox
        let image = new Image(16, 16);
        imageFromCanvas(image, image, 0);
      }
    }, 2000);
```
does it work then?

**Comment by MooseZM** [comment]
I'm not tech savvy enough to know if this will cause problems, but can't you just use Violentmonkey for this script and leave Tampermonkey to handle the rest of your scripts (that's what I'm doing and I haven't had any problems)
![image](https://github.com/drunohazarb/4chan-captcha-solver/assets/85148899/d71cc117-a615-4033-97ea-f386013c2bd8)

**Comment by OliverMD15** [comment]
@slabodan That does seem to work, not sure if it entirely fixes it yet though.
@MooseZM I'd prefer a proper fix over having to install multiple add-ons that do the same job.

**Comment by BenderBRod** [comment]
Strange, it doesnt work for me

**Comment by drunohazarb** [comment]
@BenderBRod @OliverMD15 Try these and see if they work:
https://cdn.discordapp.com/attachments/1189659012577382541/1189659179925913620/4chan-captcha-solver.user.js
https://cdn.discordapp.com/attachments/1189659012577382541/1189659179502280795/4chan-captcha-solver-wasm.user.js

I did make some changes to how the scripts load but it's pretty clear to me that this is some sort of Tampermonkey bug given that the scripts work when Tampermonkey is the only extension running on Chromium. However, if these work for you guys I'm willing to undo these changes because they're really not worth the hassle.

**Comment by OliverMD15** [comment]
Provided I didn't screw anything up, these seem to work fine on my end. 
But so did the patch from above, while it didn't for Bender.

**Comment by BenderBRod** [comment]
It works!
Tried it on a couple boards and it loaded every time.
Great job, thank you

**Comment by BenderBRod** [comment]
One last thing
How about adding an auto post feature so you dont always have to press tab 2-3 times and enter

**Comment by drunohazarb** [comment]
82423b4ca311e9ade1d0ae64b0678b95a9c6b0db

> One last thing
How about adding an auto post feature so you dont always have to press tab 2-4 times and enter
Could be opt in by commenting it out in the code

I might just add a settings page and use `GM.getValue` and `GM.setValue` to store the settings. I could even add an option to allow switching backends without the need for two different scripts.
