### ISSUE TITLE
New captcha

### ISSUE THREAD

**Issue by BenderBRod** [drunohazarb/4chan-captcha-solver#11]
Now, the letters inside the circle are white every time

![solver](https://github.com/drunohazarb/4chan-captcha-solver/assets/17176020/6a2bc522-7330-4d46-8806-53c55c3e5854)
![solver1](https://github.com/drunohazarb/4chan-captcha-solver/assets/17176020/82606ef0-2b66-43ab-8972-0c2e90cb4cf0)

Ok, not every time
![solver2](https://github.com/drunohazarb/4chan-captcha-solver/assets/17176020/215f495a-4d83-4f9e-b61a-31c34355a068)

**Comment by slabodan** [comment]
Looks like they are announcing a captcha jihad on us

**Comment by slabodan** [comment]
Wouldn't just using https://git.coom.tech/araragi/JKCS/issues/18#issuecomment-2274 and inverting the colors in the blob make the old model work again lol

**Comment by BenderBRod** [comment]
It was like 30 minutes when every circle had white letters and now its back to normal
I assume they will change it up all the time now so maybe its impossible to get a working model
I dont know.

**Comment by JonseyJones** [comment]
![Screenshot 2024-01-03 at 17-01-29 (2) _pol_ - Why hasn't there been any significant terrorist at - Politically Incorrect - 4chan](https://github.com/drunohazarb/4chan-captcha-solver/assets/35809877/26e9a374-7dd9-423f-833a-9fdc14d3b8d5)

**Comment by JonseyJones** [comment]
Chance/moffatman managed to fix it on their end, works pretty well with the white letters on the black circle.

**Comment by wewlad-dev** [comment]
In the last hour or so, the captcha solver is pointless and probably zero success rate, I think they updated the captcha, AGAIN!
![Screenshot_20240104_191333](https://github.com/drunohazarb/4chan-captcha-solver/assets/59626410/50a2a71f-1959-42c5-9f6c-81d65c350e56)

**Comment by slabodan** [comment]
mate it's been like that since this issue was opened

**Comment by DocHoncho** [comment]
It's election season, they gotta keep the bots out somehow. Although one has to wonder what the botting breakdown looks like...cuz if they're just whacking away on /b/ and /pol/ I mean, why not let them? Let the bots piss into the sea of piss

**Comment by drunohazarb** [comment]
2f20d5871479124272f527aabf119d0dbc1b9797
