### ISSUE TITLE
Captcha occasionally asks for human verification

### ISSUE THREAD

**Issue by LeeroyGarfield** [drunohazarb/4chan-captcha-solver#12]
When you click the "get captcha" button, you'll get the "checking if your connection is secure..." message and it just stuck there. 

To get around this, you have to disable the captcha solver script and then click the checkbox verifying you're a human after getting a captcha, then switch the script back on and it'll auto solve it until it asks you to verify you're a human again (behind the "checking if your connection is secure..." message).

The second captcha is powered by Cloudflare.

I don't see this issue in the list so I hope I'm not the only one.

**Comment by slabodan** [comment]
this is a styling issue, if you stretch the qr box you can see that the turnstile is there
<img width="311" alt="Screenshot 2024-01-03 at 16 30 04" src="https://github.com/drunohazarb/4chan-captcha-solver/assets/101034961/07024420-5518-4e30-a33e-2a485bd899c4">
<img width="666" alt="Screenshot 2024-01-03 at 16 30 12" src="https://github.com/drunohazarb/4chan-captcha-solver/assets/101034961/81bdd6d6-ada3-4fef-9645-f76d3a57c078">

**Comment by slabodan** [comment]
this sometimes happens to me even with the script disabled so this might be a 4chanx/4chan issue that they will fix idk

**Comment by LeeroyGarfield** [comment]
Huh, that's interesting. Didn't know you could stretch far to see that stupid Cloudflare captcha. So I'm not the only one then. Good to know.

It wasn't like this before because it would just solve itself, but now it just stuck there.

**Comment by drunohazarb** [comment]
Apparently this has been solved on 4chan's end: https://github.com/ccd0/4chan-x/issues/3432#issuecomment-1885625028
