### ISSUE TITLE
[idea] using Parseq, using the idea of Scene Text recongition 

### ISSUE THREAD

**Issue by beansofhell** [drunohazarb/4chan-captcha-solver#13]

**Comment by beansofhell** [comment]
todo for myself:
get a dataset of the new captchas
https://github.com/baudm/parseq
use [crnn](https://github.com/baudm/parseq/tree/main/strhub/models/crnn) because of low cpu usage, so can be attached to an API 
use an API with a rate limited of 5 requests per minute.

**Comment by slabodan** [comment]
I dont really know shit about AI and all that stuff but one idea I had was combining [this](https://git.coom.tech/araragi/JKCS/issues/18#issuecomment-2274) with the previous [dataset](https://github.com/drunohazarb/4chan-captcha-solver/issues/6#issuecomment-1868019836) to generate a dataset of the new captchas but idk maybe that is retarded

**Comment by Yukariin** [comment]
Current model uses similar crrn architecture, but even smaller - you don't need much for captchas of 20 characters with zero semantic. You can check the training notebook I shared in #6 for more details.
You can run this model as an API, [moffatman](https://github.com/moffatman) does that for chance iirc

**Comment by JonseyJones** [comment]
Time for @drunohazarb  to update the script then.

**Comment by JonseyJones** [comment]
> Current model uses similar crrn architecture, but even smaller - you don't need much for captchas of 20 characters with zero semantic. You can check the training notebook I shared in #6 for more details. You can run this model as an API, [moffatman](https://github.com/moffatman) does that for chance iirc

Why did the development on the script stop?
Do you have the new model?
Any news from moffatman?
How come nobody cares anymore?

**Comment by JonseyJones** [comment]
> What's wrong with current one?

Doesn't work when the white letters are on the black blob, it doesn't solve those letters/numbers.

**Comment by aaafre4** [comment]
i'm in a weird spot where i didnt want to start manual collection if moffatat drops the dataset so i was just waiting for that and didnt wanna bother him but its been a week so i started collecting today.  i'm at ~900 captchas now. if i take adderall xr i can collect 500 captchas manually per hour but its tedious as fuck so i can do it twice per day. my first script that i used for collection also was sending labels incorrectly so i also have 600 captchas with wrong labels

@Yukariin how many are needed to get 75% success rate?

**Comment by Yukariin** [comment]
> @Yukariin how many are needed to get 75% success rate?

1k should be fine for fine-tuning.
You also want an even distribution between different captcha types. For example if you have 1k new captchas (white letter in black circle) you want 1k old captchas (without circle) and 1k new-old captchas (black letter in black circle with white outline) so 3k total dataset.

**Comment by aaafre4** [comment]
here's what ive got, had to double check if i didnt fuck up the labels again lol but looks fine [captchas 1k.zip](https://github.com/drunohazarb/4chan-captcha-solver/files/13904758/captchas.1k.zip)

and if the ones with incorrect labels are useful in any way  
[captchas 600 - incorrect labels.zip](https://github.com/drunohazarb/4chan-captcha-solver/files/13904777/captchas.600.-.incorrect.labels.zip)

**Comment by JonseyJones** [comment]
>   1k old captchas (without circle) and 1k new-old captchas (black letter in black circle with white outline) so 3k total dataset.

The older captchas are the same.

**Comment by Yukariin** [comment]
> The older captchas are the same.

Yeah but you don't want model to regress on old captchas, which will happen if you train/tune **only** on new ones

**Comment by Yukariin** [comment]
> here's what ive got

Here's a test [model](https://files.catbox.moe/97kujt.h5) actives 98.9% (7655/7735) accuracy on combined large dataset (10k old + 16k new + 1k new (white letters))

**Comment by aaafre4** [comment]
tnx its already much better, i will try to bang out 2k more captchas over the weekend

**Comment by drunohazarb** [comment]
> Why did the development on the script stop?
Do you have the new model?
Any news from moffatman?
How come nobody cares anymore?

It's not that I don't care, there's just not much I can do without collecting captcha samples myself.
Anyways, I just updated the script to use Yukariin's new test model. I will push the update as soon as I can confirm that the model can solve the older captchas as well, for good measure.

As for the suggestion, I think it belongs here: https://github.com/based-org/chana-solver
