### ISSUE TITLE
Recent cuckchan captcha changes

### ISSUE THREAD

**Issue by trip54654** [drunohazarb/4chan-captcha-solver#16]
As always, 4chan changed their captcha as soon as you published a new model. Some observations:
- with the 5 or 6 letter captchas, if one letter is wrong, 4chan will pretend it accepted the catpcha, that you made the post successfully, and give you a random post number as the post you made, very annoying and was introduced some days ago (it will pretend success even if you post a duplicate file)
- this doesn't happen with the 4 letter captchas
- at least /trash/ (unlike some blue boards I tried) gets a captcha for which the slider doesn't get solved correctly

At least on blue boards, you get 4 letter captcha on a new session. They have a better auto solve hit rate and 4chan doesn't do this pretend success behavior on wrong captchas. Very weird how they punish human captcha solvers with long sessions, while probably bots or ban evaders have it easier.

**Comment by aaafre5** [comment]
I was waiting for them to come after the slider since that was the weak link on their end...

**Comment by JonseyJones** [comment]
> I was waiting for them to come after the slider since that was the weak link on their end...

The slider is fine if anything it's easier to solve with the black blob.

I didn't experience any problems at all with the latest release but I did read a few days back in some /g/ thread that some users using solvers if they post too fast their post is successful but it's not actually there so idk wait like 5 seconds before posting?!

**Comment by trip54654** [comment]
>Tested it and NO, all letters must be right in order to post, not one case as described by OP.(tested on different browsers and IPs, 10 posts)

It still happens to me. Maybe I get special treatment by IP range or user agent?

**Comment by gir489returns** [comment]
What @trip54654 is describing is not new, in fact, this was introduced several years ago to combat the BGC counterspam of the BBC on /pol/.

I used to get it erroneously for no reason, nothing I could do would fix it. Multiple browsers/IPs/files/boards, all would return successful post ID, but forward to a post that doesn't exist, which just returns you to the catalog. Probably as some kind of way to trick the bots into thinking their post worked. However, after a while of waiting, eventually it stopped and let me make more threads. The worst of this was during the video butts, trying to make a thread when he was at his worst was like next to impossible.

I have never gotten a single non-4 letter word CAPTCHA since @aaafre5's new model. I've had 391 CAPTCHAs, and 69 of them were wrong.

**Comment by aaafre5** [comment]
its @Yukariin's model thoughbeit. On that note if they fuck up the slider in other ways, is it possible for a model to solve a captcha just from the 2 captcha images alone without alignment or is it too random? 
![download (18)](https://github.com/drunohazarb/4chan-captcha-solver/assets/157304793/0f5e4f1c-78f6-4f19-bd69-c34c46d5c36c)
![download (19)](https://github.com/drunohazarb/4chan-captcha-solver/assets/157304793/bc85d248-c73c-4ba4-ba40-b2de2e4dd32a)

**Comment by Yukariin** [comment]
> is it possible for a model to solve a captcha just from the 2 captcha images alone without alignment or is it too random?

It probably won't work due to random letter fragments on the _bg_ image

**Comment by drunohazarb** [comment]
bfd186ca6861667ece8062bad74463c5c9b08eee

I added an algorithm to handle the new slider, it's not perfect but it will do for now. Also, the model can't really solve the new captchas so we'll need to collect a new dataset for it. I have collected 115 captchas so far.

I have also invited @Yukariin to be a collaborator so he can push an update with the new model as soon as possible.

**Comment by trip54654** [comment]
>I used to get it erroneously for no reason, nothing I could do would fix it. Multiple browsers/IPs/files/boards, all would return successful post ID, but forward to a post that doesn't exist, which just returns you to the catalog. Probably as some kind of way to trick the bots into thinking their post worked.

I suspect I only get it when the captcha was wrong. As of now, I never get a captcha error for 6 letter captchas. If it was right, the post shows up. If it was wrong, it pretends it got posted, but it never shows up. Anyway, it's unrelated to the captcha solver.

**Comment by aaafre5** [comment]
> Also, the model can't really solve the new captchas so we'll need to collect a new dataset for it. I have collected 115 captchas so far.
Do you get it on any board other than trash. It doesn't really affect me at the moment but I suppose its my civic duty to contribute some 'chas would be good if I can get them by posting on a different board. 

as for the regular 4 letter ones the dataset got clapped once gh shadowbanned my previous account for whatever reason so here's the 1k + 430 something captchas. 
[400smth.zip](https://github.com/drunohazarb/4chan-captcha-solver/files/14061216/400smth.zip)
[1k 2.zip](https://github.com/drunohazarb/4chan-captcha-solver/files/14061213/1k.2.zip)

**Comment by trip54654** [comment]
I think I'm seeing slider failures on blue boards. Is it possible related to trying to solve sliders on /trash/? Before this recent change, solving the slider worked absolutely reliably.

**Comment by JonseyJones** [comment]
> I think I'm seeing slider failures on blue boards. Is it possible related to trying to solve sliders on /trash/? Before this recent change, solving the slider worked absolutely reliably.

I'm not seeing any on /g/ and /tv/.

**Comment by gir489returns** [comment]
> I think I'm seeing slider failures on blue boards. Is it possible related to trying to solve sliders on /trash/? Before this recent change, solving the slider worked absolutely reliably.

Nothing on /v/ for me. Working fine.

**Comment by trip54654** [comment]
>I'm not seeing any on /g/ and /tv/.

>Nothing on /v/ for me. Working fine.

It happens only maybe 1 of 10 captchas. But it never happened before the recent change.
