### ISSUE TITLE
Something's broken

### ISSUE THREAD

**Issue by horusra** [drunohazarb/4chan-captcha-solver#18]
Using 
Windows 10
LibreWolf 121.0-1
ViolentMonkey 2.18.0
4chan-x 1.14.22.4 (userscript)

The result:
![librewolf_VSBxrxcFhM](https://github.com/drunohazarb/4chan-captcha-solver/assets/17074394/6ed16179-773b-412d-95b4-c928a2b40232)

Anyone know what the cause of this could be?

it's not cookies
![image](https://github.com/drunohazarb/4chan-captcha-solver/assets/17074394/b21e2f50-5e59-4fee-80d5-8b0400bc3bdb)

**Comment by JonseyJones** [comment]
Same setup but ff as browser, no such problem or any.

**Comment by gir489returns** [comment]
Working fine for me on Edge.

**Comment by aaafre5** [comment]
> LibreWolf 121.0-1

Haha. I think it has something to do with canvas. What does the image look like if you save the captcha?

**Comment by drunohazarb** [comment]
You need to grant canvas permission to 4chan.org for the script to work. That's what's wrong.

**Comment by trip54654** [comment]
Unrelated, but is there a reason why the non-wasm version has a space at the start of the script? I need to fix the space on every update, because it doesn't parse the header correctly and doesn't get the tf dependency.

**Comment by drunohazarb** [comment]
Oh shit I must be blind

45667191864e2ada4b1f882c6c1be86d07133ee4

**Comment by ghost** [comment]
Allowing canvas fixed it 👍
Thanks for also including it in the readme for others to know
