### ISSUE TITLE
Include sys.4channel.org

### ISSUE THREAD

**Issue by badadv** [drunohazarb/4chan-captcha-solver#2]
Currently this script doesn't run on the captcha needed for reporting posts in blue boards. Red boards use sys.4chan.org which it does run on.
Adding this line below the one for sys.4chan.org seems to work perfectly fine: 
`// @match       https://sys.4channel.org/*`

**Comment by drunohazarb** [comment]
0ad7f6f312bd0d3be132b8ded5bf9e4c6c3923a5
