### ISSUE TITLE
what  does "save captcha" do?

### ISSUE THREAD

**Issue by Theo1996** [drunohazarb/4chan-captcha-solver#25]
as the the title asks...

**Comment by trip54654** [comment]
It saves the captcha when posting. Surprised? Look at your download folder. It's really useless and the checkbox takes a lot of space. I'd rather have a feature that saves captcha when solving/posting fails.

**Comment by Theo1996** [comment]
I see.

**Comment by trip54654** [comment]
By the way, they really should get rid of it. It's useless.

**Comment by gir489returns** [comment]
> By the way, they really should get rid of it. It's useless.

When the 4cuck jannies update the CAPTCHA again we will need it to gather samples to create a new model. Probably around November when election season kicks into high gear they will start fighting it again.
