### ISSUE TITLE
Another captcha change

### ISSUE THREAD

**Issue by trip54654** [drunohazarb/4chan-captcha-solver#28]
![WRA4](https://github.com/user-attachments/assets/f1383967-57c7-455c-905f-28bec01eb015)

Saw this today on a new IP. I'm still getting the old captchas on older cookie/IP. The model can't solve this and generally has a low success rate on them.

**Comment by slabodan** [comment]
What board? Haven't seen this one at all even on new IPs.

**Comment by trip54654** [comment]
Didn't get it again in over a week... I must have hit a strange heuristic and maybe this isn't even new.
