### ISSUE TITLE
explain it to me like im stupid, please

### ISSUE THREAD

**Issue by adsobi0621** [drunohazarb/4chan-captcha-solver#34]
how do i install this thing, im a genuine idiot so i have no clue what to do.

**Comment by slabodan** [comment]
get a userscript extension
chrome: https://chromewebstore.google.com/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=en
firefox: https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/

open https://github.com/drunohazarb/4chan-captcha-solver/raw/refs/heads/new_captcha/4chan-captcha-solver-wasm.user.js

click install

**Comment by adsobi0621** [comment]
thank you very much for explaining it to me like im stupid, anon
