### ISSUE TITLE
Fresh new captcha, slider isn't accurate anymore

### ISSUE THREAD

**Issue by INDIANUMBERONE** [drunohazarb/4chan-captcha-solver#37]
![2H2NMY](https://github.com/user-attachments/assets/7b276502-fe7a-4f67-87a6-bc469c47f2ee)

100 examples: 
[Oct_23.zip](https://github.com/user-attachments/files/17500091/Oct_23.zip)

**Comment by INDIANUMBERONE** [comment]
500 captchas
[500.zip](https://github.com/user-attachments/files/17515763/500.zip)

**Comment by gtaltatra** [comment]
Ok but why did you close it? This one seems consistent unlike other variants implemented recently. 
Yes it usually switches to the older one, but only after several hours or so

**Comment by INDIANUMBERONE** [comment]
> Ok but why did you close it? This one seems consistent unlike other variants implemented recently. Yes it usually switches to the older one, but only after several hours or so

It was fixed in "new captcha"
Doesn't work anymore though, they changed it again
