### ISSUE TITLE
New capcha model just dropped!

### ISSUE THREAD

**Issue by JonseyJones** [drunohazarb/4chan-captcha-solver#6]
![Screenshot 2023-12-18 at 18-51-50 (4) _pol_ - Realistically how does Biden recover from this - Politically Incorrect - 4chan](https://github.com/drunohazarb/4chan-captcha-solver/assets/35809877/2f0f26e2-033e-47be-86a4-511f55315da6)
It has a big black circle with a random position.

**Comment by Kuwoshii** [comment]
you vil align ze circle and you vil like it

![image](https://github.com/drunohazarb/4chan-captcha-solver/assets/102769991/43be0e42-ba46-49b1-9fe7-cce457d070c4)

**Comment by CaptainChicky** [comment]
well if someone is able to manually compile a dataset of captchas+solutions (rip) they could retrain the net

**Comment by LittleEndu** [comment]
how many examples would be required to retrain the model? Current model even gets the circle correct some of the time

**Comment by gir489returns** [comment]
> you vil align ze circle and you vil like it
> 
> ![image](https://private-user-images.githubusercontent.com/102769991/291675758-43be0e42-ba46-49b1-9fe7-cce457d070c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxOTU5NTYsIm5iZiI6MTcwMzE5NTY1NiwicGF0aCI6Ii8xMDI3Njk5OTEvMjkxNjc1NzU4LTQzYmUwZTQyLWJhNDYtNDliMS05ZmU3LWNjZTQ1N2QwNzBjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQyMTU0MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGE3YmMwNzNhOWFiNWQxZmUzMjE0N2VkNjg1MjJjNzdlZTM5ODRmZDA5OWVjOTY3Y2NiZWJiODZkZmQ2MmZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QSlgw7AIAMRQuZeF_nxaUEBEgqkm1VJdtGs2wvCgtyY)

![image](https://github.com/drunohazarb/4chan-captcha-solver/assets/100792176/7af06d46-0521-4951-a2f8-8bf51e0e5550)

**Comment by moffatman** [comment]
16k images of new captcha, it was able to converge since since 4k+, surprisingly easy
https://captcha.chance.surf/bundle_16kblack/images.zip
https://captcha.chance.surf/bundle_16kblack/model.h5

**Comment by drunohazarb** [comment]
@moffatman Thanks a bunch for training the model!

7826d5ae53da72a6cf64dd2a82a4a3f5aec557b9

**Comment by Yukariin** [comment]
> it was able to converge since since 4k+, surprisingly easy
Was it really?
Accuracy for old captchas (still in use) is ~78% but feels even lower - like 3-4 of 10 captchas being solved correctly.
Fine-tuned @moffatman 16k model on combined dataset - 10k old + 16k new captchas from @moffatman and 3.5k old captchas from @coomdev. Achieves 98.7% (7388/7485) accuracy.
[model](https://files.catbox.moe/dff01b.h5)
[notebook](https://files.catbox.moe/1hx65g.ipynb)

Also I'd recommend to use latest trained model to sanitise your own dataset - both old 10k and new 16k (and coomtech's one) contain some misaligned and/or mislabeled captchas.

**Comment by moffatman** [comment]
@Yukariin 
Ah, a hybrid model, really interesting! I didn't realize the simpler captcha still gets served sometimes. I have a lot more data, probably a million+ old captchas, and growing number of new captchas (50k atm). So I will play around with it. Thanks for all your contribution here!!

I did notice some misaligned, since I get most of these from kuroba users, and it doesn't use optimal alignment method.
