### ISSUE TITLE
New captcha model gets old captchas wrong

### ISSUE THREAD

**Issue by MooseZM** [drunohazarb/4chan-captcha-solver#7]
I still get the old captcha sometimes and after updating the script it pretty much never gets it right (it used to work pretty much perfectly). It's solving the new captcha (the black circle one) just fine though. Pic rel is an example 
![image](https://github.com/drunohazarb/4chan-captcha-solver/assets/85148899/97156c84-cadc-461d-8b37-baaa0e26c509)

**Comment by rancer4** [comment]
ill add a updoot to this post.  the new ones are wrong a whole lot now.  it gets the black circle ones correct tho fairly well.  shieet

**Comment by drunohazarb** [comment]
I believe @Yukariin's new model solves this.

b9bbb4169b76d6543045751a16ef555afe702f35

**Comment by JonseyJones** [comment]
> I believe @Yukariin's new model solves this.
> 
> [b9bbb41](https://github.com/drunohazarb/4chan-captcha-solver/commit/b9bbb4169b76d6543045751a16ef555afe702f35)

Lovely job @drunohazarb & @Yukariin you guys are true solid fellows. Much appreciated!
