### ISSUE TITLE
WebAssembly version doesn't work in tampermonkey

### ISSUE THREAD

**Issue by LittleEndu** [drunohazarb/4chan-captcha-solver#8]
Doesn't work Chrome Version 120.0.6099.111 + Tampermonkey v5.0.0

but works fine with Violentmonkey 2.16.0 🤷 idk maybe worth mentioning in readme

**Comment by drunohazarb** [comment]
I tried to replicate your setup but it works just fine for me on Chromium 120.0.6099.129 + Tampermonkey 5.0.0; both with and without 4chan X.

Are there any errors in your console output?

**Comment by LittleEndu** [comment]
I'll get the logs when I actually get a captcha, getting only "Verification not required." right now xd

**Comment by LittleEndu** [comment]
logs when tampermonkey
![logs when tampermonkey](https://github.com/drunohazarb/4chan-captcha-solver/assets/11320483/2e1d7e41-ed1f-456f-bfc9-cfde1957305f)

logs when violentmonkey (null is it solving a captcha that didn't have a slider)
![logs when violentmonkey](https://github.com/drunohazarb/4chan-captcha-solver/assets/11320483/468901d1-d0a4-4d17-be58-d367bd6237ff)

**Comment by drunohazarb** [comment]
None of those errors seem to be related with the captcha solver. Very odd. Do you have any other extensions or 4chan userscripts installed? And if so, have you tried disabling them?
I'm completely clueless but since the script seems to work on my install of Chromium with just Tampermokey + the solver and 4chan X it makes me wonder if there's something else interfering with Tampermonkey.

**Comment by LittleEndu** [comment]
It seems uBlock origin is blocking it when ran on tampermonkey. oh, and it seems the regular version of the script also isn't working anymore, could have sworn it worked before (and the version before the black spot did work)🤷

**Comment by drunohazarb** [comment]
Can confirm. uBlock + Tampermonkey seems to break the script on Chromium, but it works fine on Firefox.
You might want to report this issue here:
https://github.com/Tampermonkey/tampermonkey/issues
https://github.com/uBlockOrigin/uBlock-issues/issues

**Comment by LittleEndu** [comment]
I wouldn't know what to report there :P 

also this is exactly the reason why I have both tamper and violent installed, I'll just leave this script to run in violentmonkey

**Comment by drunohazarb** [comment]
7e55d009d190ea065051ae7f5df460e5b5ca2731

Can you see if the script works on tampermonkey now?

**Comment by LittleEndu** [comment]
tried only once but seems to work on tampermonkey now
