### ISSUE TITLE
Captcha solver doesnt work for me in chrome and ungoogled-chromium

### ISSUE THREAD

**Issue by blueslippers** [drunohazarb/4chan-captcha-solver#9]
I have a windows 10 machine. After your newest update today the captcha solver doesnt work anymore. 
This works on both Opera and Firefox while its not working on both ungoogled chromium 120.0.6099.129 and chrome 104.0.5112.102.
I tried it on both tampermonkey and violentmonkey with the same results
There was no error nor any log at all about the script on the console log.

update:
violentmonkey does work with ublock. unforunately it still doesnt work on chrome with or without ublock

**Comment by blueslippers** [comment]
i dont know what happened but its fixed now.

**Comment by slabodan** [comment]
it doesn't call the DOMContentLoaded event for whatever reason i just replaced it with 

```
    window.setTimeout(function() {
      observer.observe(document.body, { attributes: true, childList: true, subtree: true });
  
      if(navigator.userAgent.toLowerCase().indexOf('firefox') !== -1){ // request canvas permission on firefox
        let image = new Image(16, 16);
        imageFromCanvas(image, image, 0);
      }
    }, 2000);
```

fuck it, works for me

**Comment by drunohazarb** [comment]
Seems like swapping the "DOMContentLoaded" event for "load" does the trick as well. Can you guys confirm this?

**Comment by slabodan** [comment]
yeah that also worked on chrome and firefox. sometimes i get this error coming from tensorflow (?) but refreshing usually fixes it, maybe it's just me 
<img width="939" alt="Screenshot 2023-12-26 at 14 09 01" src="https://github.com/drunohazarb/4chan-captcha-solver/assets/101034961/929ef7c0-d742-4657-90b7-694125e256d9">

**Comment by drunohazarb** [comment]
7e55d009d190ea065051ae7f5df460e5b5ca2731

> yeah that also worked on chrome and firefox. sometimes i get this error coming from tensorflow (?) but refreshing usually fixes it, maybe it's just me
> -img snip-
I don't think I ever ran into that one but I'll keep an eye on it and see if there's anything I do about it
